In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv(r"C:/Users/Akshat Joshi/downloads/Lead Scoring Assignment/Leads.csv")

In [4]:
df

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [5]:
df.shape

(9240, 37)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Prospect ID                                    9240 non-null   object
 1   Lead Number                                    9240 non-null   int64
 2   Lead Origin                                    9240 non-null   object
 3   Lead Source                                    9204 non-null   object
 4   Do Not Email                                   9240 non-null   object
 5   Do Not Call                                    9240 non-null   object
 6   Converted                                      9240 non-null   int64
 7   TotalVisits                                    9103 non-null   float64
 8   Total Time Spent on Website                    9240 non-null   int64
 9   Page Views Per Visit                           9103 non-null   float64
 10  Last Activity                                  9137 non-null   object
 11  Country                                        6779 non-null   object
 12  Specialization                                 7802 non-null   object
 13  How did you hear about X Education             7033 non-null   object
 14  What is your current occupation                6550 non-null   object
 15  What matters most to you in choosing a course  6531 non-null   object
 16  Search                                         9240 non-null   object
 17  Magazine                                       9240 non-null   object
 18  Newspaper Article                              9240 non-null   object
 19  X Education Forums                             9240 non-null   object
 20  Newspaper                                      9240 non-null   object
 21  Digital Advertisement                          9240 non-null   object
 22  Through Recommendations                        9240 non-null   object
 23  Receive More Updates About Our Courses         9240 non-null   object
 24  Tags                                           5887 non-null   object
 25  Lead Quality                                   4473 non-null   object
 26  Update me on Supply Chain Content              9240 non-null   object
 27  Get updates on DM Content                      9240 non-null   object
 28  Lead Profile                                   6531 non-null   object
 29  City                                           7820 non-null   object
 30  Asymmetrique Activity Index                    5022 non-null   object
 31  Asymmetrique Profile Index                     5022 non-null   object
 32  Asymmetrique Activity Score                    5022 non-null   float64
 33  Asymmetrique Profile Score                     5022 non-null   float64
 34  I agree to pay the amount through cheque       9240 non-null   object
 35  A free copy of Mastering The Interview         9240 non-null   object
 36  Last Notable Activity                          9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.6+ MB

In [7]:
df.describe()

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
count,9240.000000,9240.000000,9103.000000,9240.000000,9103.000000,5022.000000,5022.000000
mean,617188.435606,0.385390,3.445238,487.698268,2.362820,14.306252,16.344883
std,23405.995698,0.486714,4.854853,548.021466,2.161418,1.386694,1.811395
min,579533.000000,0.000000,0.000000,0.000000,0.000000,7.000000,11.000000
25%,596484.500000,0.000000,1.000000,12.000000,1.000000,14.000000,15.000000
50%,615479.000000,0.000000,3.000000,248.000000,2.000000,14.000000,16.000000
75%,637387.250000,1.000000,5.000000,936.000000,3.000000,15.000000,18.000000
max,660737.000000,1.000000,251.000000,2272.000000,55.000000,18.000000,20.000000

In [8]:
round(df.isnull().sum() / len(df) * 100,2)

Prospect ID                                       0.00
Lead Number                                       0.00
Lead Origin                                       0.00
Lead Source                                       0.39
Do Not Email                                      0.00
Do Not Call                                       0.00
Converted                                         0.00
TotalVisits                                       1.48
Total Time Spent on Website                       0.00
Page Views Per Visit                              1.48
Last Activity                                     1.11
Country                                          26.63
Specialization                                   15.56
How did you hear about X Education               23.89
What is your current occupation                  29.11
What matters most to you in choosing a course    29.32
Search                                            0.00
Magazine                                          0.00
Newspaper Article                                 0.00
X Education Forums                                0.00
Newspaper                                         0.00
Digital Advertisement                             0.00
Through Recommendations                           0.00
Receive More Updates About Our Courses            0.00
Tags                                             36.29
Lead Quality                                     51.59
Update me on Supply Chain Content                 0.00
Get updates on DM Content                         0.00
Lead Profile                                     29.32
City                                             15.37
Asymmetrique Activity Index                      45.65
Asymmetrique Profile Index                       45.65
Asymmetrique Activity Score                      45.65
Asymmetrique Profile Score                       45.65
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [9]:
df["Country"].value_counts()

Country
India                   6492
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Hong Kong                  7
Bahrain                    7
Oman                       6
France                     6
unknown                    5
South Africa               4
Nigeria                    4
Germany                    4
Kuwait                     4
Canada                     4
Sweden                     3
China                      2
Asia/Pacific Region        2
Uganda                     2
Bangladesh                 2
Italy                      2
Belgium                    2
Netherlands                2
Ghana                      2
Philippines                2
Russia                     1
Switzerland                1
Vietnam                    1
Denmark                    1
Tanzania                   1
Liberia                    1
Malaysia                   1
Kenya                      1
Sri Lanka                  1
Indonesia                  1
Name: count, dtype: int64

In [10]:
df["Country"].replace(np.nan,"Select",inplace = True)

In [11]:
df["Specialization"].value_counts()

Specialization
Select                               1942
Finance Management                    976
Human Resource Management             848
Marketing Management                  838
Operations Management                 503
Business Administration               403
IT Projects Management                366
Supply Chain Management               349
Banking, Investment And Insurance     338
Travel and Tourism                    203
Media and Advertising                 203
International Business                178
Healthcare Management                 159
Hospitality Management                114
E-COMMERCE                            112
Retail Management                     100
Rural and Agribusiness                 73
E-Business                             57
Services Excellence                    40
Name: count, dtype: int64

In [12]:
df["Specialization"].replace(np.nan,"Select",inplace = True)

In [13]:
df["How did you hear about X Education"].value_counts()

How did you hear about X Education
Select                   5043
Online Search             808
Word Of Mouth             348
Student of SomeSchool     310
Other                     186
Multiple Sources          152
Advertisements             70
Social Media               67
Email                      26
SMS                        23
Name: count, dtype: int64

In [14]:
df["How did you hear about X Education"].replace(np.nan,"Select",inplace = True)

In [15]:
df["What is your current occupation"].value_counts()

What is your current occupation
Unemployed              5600
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: count, dtype: int64

In [16]:
df["What is your current occupation"].replace(np.nan,"Select",inplace = True)

In [17]:
df["What matters most to you in choosing a course"].value_counts()

What matters most to you in choosing a course
Better Career Prospects      6528
Flexibility & Convenience       2
Other                           1
Name: count, dtype: int64

In [18]:
df["What matters most to you in choosing a course"].replace(np.nan,"Better Career Prospects",inplace = True)

In [19]:
df["Tags"].value_counts()

Tags
Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: count, dtype: int64

In [20]:
df["Tags"].replace(np.nan,"No Comments",inplace = True)

In [21]:
df["Lead Quality"].value_counts()

Lead Quality
Might be             1560
Not Sure             1092
High in Relevance     637
Worst                 601
Low in Relevance      583
Name: count, dtype: int64

In [22]:
df["Lead Quality"].replace(np.nan,"Missing",inplace = True)

In [23]:
df["Lead Profile"].value_counts()

Lead Profile
Select                         4146
Potential Lead                 1613
Other Leads                     487
Student of SomeSchool           241
Lateral Student                  24
Dual Specialization Student      20
Name: count, dtype: int64

In [24]:
df["Lead Profile"].replace(np.nan,"Select",inplace = True)

In [25]:
df["City"].value_counts()

City
Mumbai                         3222
Select                         2249
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: count, dtype: int64

In [26]:
df["City"].replace(np.nan,"Select",inplace = True)

In [27]:
df["Asymmetrique Activity Index"].value_counts()

Asymmetrique Activity Index
02.Medium    3839
01.High       821
03.Low        362
Name: count, dtype: int64

In [28]:
df["Asymmetrique Activity Index"].replace(np.nan,"Select",inplace = True)

In [29]:
df["Asymmetrique Profile Index"].value_counts()

Asymmetrique Profile Index
02.Medium    2788
01.High      2203
03.Low         31
Name: count, dtype: int64

In [30]:
df["Asymmetrique Profile Index"].replace(np.nan,"Select",inplace = True)

In [31]:
df["Asymmetrique Activity Score"].value_counts()

Asymmetrique Activity Score
14.0    1771
15.0    1293
13.0     775
16.0     467
17.0     349
12.0     196
11.0      95
10.0      57
9.0        9
18.0       5
8.0        4
7.0        1
Name: count, dtype: int64

In [32]:
df["Asymmetrique Activity Score"].replace(np.nan,14.0,inplace = True)

In [33]:
df["Asymmetrique Profile Score"].value_counts()

Asymmetrique Profile Score
15.0    1759
18.0    1071
16.0     599
17.0     579
20.0     308
19.0     245
14.0     226
13.0     204
12.0      22
11.0       9
Name: count, dtype: int64

In [34]:
df["Asymmetrique Profile Score"].replace(np.nan,15.0,inplace = True)

In [35]:
round(df.isnull().sum() / len(df) * 100,2)

Prospect ID                                      0.00
Lead Number                                      0.00
Lead Origin                                      0.00
Lead Source                                      0.39
Do Not Email                                     0.00
Do Not Call                                      0.00
Converted                                        0.00
TotalVisits                                      1.48
Total Time Spent on Website                      0.00
Page Views Per Visit                             1.48
Last Activity                                    1.11
Country                                          0.00
Specialization                                   0.00
How did you hear about X Education               0.00
What is your current occupation                  0.00
What matters most to you in choosing a course    0.00
Search                                           0.00
Magazine                                         0.00
Newspaper Article                                0.00
X Education Forums                               0.00
Newspaper                                        0.00
Digital Advertisement                            0.00
Through Recommendations                          0.00
Receive More Updates About Our Courses           0.00
Tags                                             0.00
Lead Quality                                     0.00
Update me on Supply Chain Content                0.00
Get updates on DM Content                        0.00
Lead Profile                                     0.00
City                                             0.00
Asymmetrique Activity Index                      0.00
Asymmetrique Profile Index                       0.00
Asymmetrique Activity Score                      0.00
Asymmetrique Profile Score                       0.00
I agree to pay the amount through cheque         0.00
A free copy of Mastering The Interview           0.00
Last Notable Activity                            0.00
dtype: float64

In [36]:
for cols in df.columns:
    if df[cols].dtypes == "object":
        print("\n",cols,":",df[cols].value_counts())

 Prospect ID : Prospect ID
7927b2df-8bba-4d29-b9a2-b6e0beafe620    1
22e9d4ef-d294-4ebf-81c7-7c7a1105aeea    1
46befc49-253a-419b-abea-2fd978d2e2b1    1
9d35a2c2-09d8-439f-9875-0e8bbf267f5a    1
f0de9371-4dc2-48c2-9785-a08d6fc4fcb5    1
                                       ..
ff1f7582-cb7b-4b94-9cdc-3d0d0afdd9a3    1
644099a2-3da4-4d23-9546-7676340a372b    1
2a093175-415b-4321-9e69-ed8d9df65a3c    1
c66249a3-8500-4c66-a511-312d914573de    1
571b5c8e-a5b2-4d57-8574-f2ffb06fdeff    1
Name: count, Length: 9240, dtype: int64

 Lead Origin : Lead Origin
Landing Page Submission    4886
API                        3580
Lead Add Form               718
Lead Import                  55
Quick Add Form                1
Name: count, dtype: int64

 Lead Source : Lead Source
Google               2868
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
bing                    6
google                  5
Click2call              4
Press_Release           2
Social Media            2
Live Chat               2
youtubechannel          1
testone                 1
Pay per Click Ads       1
welearnblog_Home        1
WeLearn                 1
blog                    1
NC_EDM                  1
Name: count, dtype: int64

 Do Not Email : Do Not Email
No     8506
Yes     734
Name: count, dtype: int64

 Do Not Call : Do Not Call
No     9238
Yes       2
Name: count, dtype: int64

 Last Activity : Last Activity
Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: count, dtype: int64

 Country : Country
India                   6492
Select                  2461
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Bahrain                    7
Hong Kong                  7
Oman                       6
France                     6
unknown                    5
Kuwait                     4
South Africa               4
Canada                     4
Nigeria                    4
Germany                    4
Sweden                     3
Philippines                2
Uganda                     2
Italy                      2
Bangladesh                 2
Netherlands                2
Asia/Pacific Region        2
China                      2
Belgium                    2
Ghana                      2
Kenya                      1
Sri Lanka                  1
Tanzania                   1
Malaysia                   1
Liberia                    1
Switzerland                1
Denmark                    1
Russia                     1
Vietnam                    1
Indonesia                  1
Name: count, dtype: int64

 Specialization : Specialization
Select                               3380
Finance Management                    976
Human Resource Management             848
Marketing Management                  838
Operations Management                 503
Business Administration               403
IT Projects Management                366
Supply Chain Management               349
Banking, Investment And Insurance     338
Travel and Tourism                    203
Media and Advertising                 203
International Business                178
Healthcare Management                 159
Hospitality Management                114
E-COMMERCE                            112
Retail Management                     100
Rural and Agribusiness                 73
E-Business                             57
Services Excellence                    40
Name: count, dtype: int64

 How did you hear about X Education : How did you hear about X Education
Select                   7250
Online Search             808
Word Of Mouth             348
Student of SomeSchool     310
Other                     186
Multiple Sources          152
Advertisements             70
Social Media               67
Email                      26
SMS                        23
Name: count, dtype: int64

 What is your current occupation : What is your current occupation
Unemployed              5600
Select                  2690
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: count, dtype: int64

 What matters most to you in choosing a course : What matters most to you in choosing a course
Better Career Prospects      9237
Flexibility & Convenience       2
Other                           1
Name: count, dtype: int64

 Search : Search
No     9226
Yes      14
Name: count, dtype: int64

 Magazine : Magazine
No    9240
Name: count, dtype: int64

 Newspaper Article : Newspaper Article
No     9238
Yes       2
Name: count, dtype: int64

 X Education Forums : X Education Forums
No     9239
Yes       1
Name: count, dtype: int64

 Newspaper : Newspaper
No     9239
Yes       1
Name: count, dtype: int64

 Digital Advertisement : Digital Advertisement
No     9236
Yes       4
Name: count, dtype: int64

 Through Recommendations : Through Recommendations
No     9233
Yes       7
Name: count, dtype: int64

 Receive More Updates About Our Courses : Receive More Updates About Our Courses
No    9240
Name: count, dtype: int64

 Tags : Tags
No Comments                                          3353
Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: count, dtype: int64

 Lead Quality : Lead Quality
Missing              4767
Might be             1560
Not Sure             1092
High in Relevance     637
Worst                 601
Low in Relevance      583
Name: count, dtype: int64

 Update me on Supply Chain Content : Update me on Supply Chain Content
No    9240
Name: count, dtype: int64

 Get updates on DM Content : Get updates on DM Content
No    9240
Name: count, dtype: int64

 Lead Profile : Lead Profile
Select                         6855
Potential Lead                 1613
Other Leads                     487
Student of SomeSchool           241
Lateral Student                  24
Dual Specialization Student      20
Name: count, dtype: int64

 City : City
Select                         3669
Mumbai                         3222
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: count, dtype: int64

 Asymmetrique Activity Index : Asymmetrique Activity Index
Select       4218
02.Medium    3839
01.High       821
03.Low        362
Name: count, dtype: int64

 Asymmetrique Profile Index : Asymmetrique Profile Index
Select       4218
02.Medium    2788
01.High      2203
03.Low         31
Name: count, dtype: int64

 I agree to pay the amount through cheque : I agree to pay the amount through cheque
No    9240
Name: count, dtype: int64

 A free copy of Mastering The Interview : A free copy of Mastering The Interview
No     6352
Yes    2888
Name: count, dtype: int64

 Last Notable Activity : Last Notable Activity
Modified                        3407
Email Opened                    2827
SMS Sent                        2172
Page Visited on Website          318
Olark Chat Conversation          183
Email Link Clicked               173
Email Bounced                     60
Unsubscribed                      47
Unreachable                       32
Had a Phone Conversation          14
Email Marked Spam                  2
Approached upfront                 1
Resubscribed to emails             1
View in browser link Clicked       1
Form Submitted on Website          1
Email Received                     1
Name: count, dtype: int64

In [37]:
df.drop(["Magazine","Receive More Updates About Our Courses","Update me on Supply Chain Content","Get updates on DM Content","I agree to pay the amount through cheque","Lead Number","Prospect ID"],axis = 1, inplace = True)

In [38]:
bin_map = ["Do Not Email","Do Not Call","Search","Newspaper Article","X Education Forums","Newspaper","Digital Advertisement","Through Recommendations","A free copy of Mastering The Interview"]

In [39]:
def BinaryMapping(x):
    return x.map({"Yes" : 1, "No" : 0})

In [40]:
df[bin_map] = df[bin_map].apply(BinaryMapping)

In [41]:
df.dropna(inplace = True)

In [42]:
df.isnull().sum()

Lead Origin                                      0
Lead Source                                      0
Do Not Email                                     0
Do Not Call                                      0
Converted                                        0
TotalVisits                                      0
Total Time Spent on Website                      0
Page Views Per Visit                             0
Last Activity                                    0
Country                                          0
Specialization                                   0
How did you hear about X Education               0
What is your current occupation                  0
What matters most to you in choosing a course    0
Search                                           0
Newspaper Article                                0
X Education Forums                               0
Newspaper                                        0
Digital Advertisement                            0
Through Recommendations                          0
Tags                                             0
Lead Quality                                     0
Lead Profile                                     0
City                                             0
Asymmetrique Activity Index                      0
Asymmetrique Profile Index                       0
Asymmetrique Activity Score                      0
Asymmetrique Profile Score                       0
A free copy of Mastering The Interview           0
Last Notable Activity                            0
dtype: int64

In [43]:
encoded_cols = pd.get_dummies(df[["Lead Origin","What is your current occupation","What matters most to you in choosing a course","Lead Quality","Lead Profile","City"]],drop_first = True,dtype= int)

In [44]:
encoded_cols

,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,What is your current occupation_Housewife,What is your current occupation_Other,What is your current occupation_Select,What is your current occupation_Student,What is your current occupation_Unemployed,What is your current occupation_Working Professional,What matters most to you in choosing a course_Flexibility & Convenience,...,Lead Profile_Other Leads,Lead Profile_Potential Lead,Lead Profile_Select,Lead Profile_Student of SomeSchool,City_Other Cities,City_Other Cities of Maharashtra,City_Other Metro Cities,City_Select,City_Thane & Outskirts,City_Tier II Cities
0,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
2,1,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
9236,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
9237,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
9238,1,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
9239,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0

In [45]:
freq_variables = ["Lead Source","Country","Specialization","Last Activity",'How did you hear about X Education',"Last Notable Activity","Tags"]

In [46]:
df2 = df[["Lead Source","Country","Specialization","Last Activity",'How did you hear about X Education',"Last Notable Activity","Tags"]]

In [47]:
df2

,Lead Source,Country,Specialization,Last Activity,How did you hear about X Education,Last Notable Activity,Tags
0,Olark Chat,Select,Select,Page Visited on Website,Select,Modified,Interested in other courses
1,Organic Search,India,Select,Email Opened,Select,Email Opened,Ringing
2,Direct Traffic,India,Business Administration,Email Opened,Select,Email Opened,Will revert after reading the email
3,Direct Traffic,India,Media and Advertising,Unreachable,Word Of Mouth,Modified,Ringing
4,Google,India,Select,Converted to Lead,Other,Modified,Will revert after reading the email
...,...,...,...,...,...,...,...
9235,Direct Traffic,Saudi Arabia,IT Projects Management,Email Marked Spam,Select,Email Marked Spam,Will revert after reading the email
9236,Direct Traffic,India,Media and Advertising,SMS Sent,Select,SMS Sent,wrong number given
9237,Direct Traffic,India,Business Administration,SMS Sent,Select,SMS Sent,invalid number
9238,Google,India,Human Resource Management,SMS Sent,Online Search,SMS Sent,No Comments
9239,Direct Traffic,Bangladesh,Supply Chain Management,SMS Sent,Select,Modified,Will revert after reading the email

In [48]:
def frequency_encoding(df, variables):
    # Create a copy of the dataframe to avoid modifying the original data
    df_encoded = df.copy()
    
    for var in variables:
        # Calculate the frequency of each category
        freq = df[var].value_counts(normalize=True)
        # Map the frequency to the original column
        df_encoded[var] = df[var].map(freq)
    
    return df_encoded

In [49]:
df_encoded = frequency_encoding(df2, freq_variables)

In [50]:
df_encoded

,Lead Source,Country,Specialization,Last Activity,How did you hear about X Education,Last Notable Activity,Tags
0,0.193189,0.253031,0.361693,0.070531,0.780912,0.360040,0.056094
1,0.127177,0.715341,0.361693,0.378223,0.780912,0.311109,0.130813
2,0.280251,0.715341,0.043972,0.378223,0.780912,0.311109,0.222173
3,0.280251,0.715341,0.022261,0.009918,0.038241,0.360040,0.130813
4,0.316068,0.715341,0.361693,0.047168,0.020498,0.360040,0.222173
...,...,...,...,...,...,...,...
9235,0.280251,0.002314,0.040335,0.000220,0.780912,0.000220,0.222173
9236,0.280251,0.715341,0.022261,0.299317,0.780912,0.237161,0.005180
9237,0.280251,0.715341,0.043972,0.299317,0.780912,0.237161,0.009147
9238,0.316068,0.715341,0.092242,0.299317,0.089046,0.237161,0.366652
9239,0.280251,0.000220,0.038131,0.299317,0.780912,0.360040,0.222173

In [51]:
df1 = pd.concat([df,encoded_cols],axis=1)

In [52]:
df1

,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,...,Lead Profile_Other Leads,Lead Profile_Potential Lead,Lead Profile_Select,Lead Profile_Student of SomeSchool,City_Other Cities,City_Other Cities of Maharashtra,City_Other Metro Cities,City_Select,City_Thane & Outskirts,City_Tier II Cities
0,API,Olark Chat,0,0,0,0.0,0,0.00,Page Visited on Website,Select,...,0,0,1,0,0,0,0,1,0,0
1,API,Organic Search,0,0,0,5.0,674,2.50,Email Opened,India,...,0,0,1,0,0,0,0,1,0,0
2,Landing Page Submission,Direct Traffic,0,0,1,2.0,1532,2.00,Email Opened,India,...,0,1,0,0,0,0,0,0,0,0
3,Landing Page Submission,Direct Traffic,0,0,0,1.0,305,1.00,Unreachable,India,...,0,0,1,0,0,0,0,0,0,0
4,Landing Page Submission,Google,0,0,1,2.0,1428,1.00,Converted to Lead,India,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,0,1,8.0,1845,2.67,Email Marked Spam,Saudi Arabia,...,0,1,0,0,0,0,0,0,0,0
9236,Landing Page Submission,Direct Traffic,0,0,0,2.0,238,2.00,SMS Sent,India,...,0,1,0,0,0,0,0,0,0,0
9237,Landing Page Submission,Direct Traffic,1,0,0,2.0,199,2.00,SMS Sent,India,...,0,1,0,0,0,0,0,0,0,0
9238,Landing Page Submission,Google,0,0,1,3.0,499,3.00,SMS Sent,India,...,0,0,1,0,0,0,1,0,0,0
9239,Landing Page Submission,Direct Traffic,0,0,1,6.0,1279,3.00,SMS Sent,Bangladesh,...,0,1,0,0,1,0,0,0,0,0

In [53]:
df3 = pd.concat([df1,df2],axis=1)

In [54]:
df3

,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,...,City_Select,City_Thane & Outskirts,City_Tier II Cities,Lead Source,Country,Specialization,Last Activity,How did you hear about X Education,Last Notable Activity,Tags
0,API,Olark Chat,0,0,0,0.0,0,0.00,Page Visited on Website,Select,...,1,0,0,Olark Chat,Select,Select,Page Visited on Website,Select,Modified,Interested in other courses
1,API,Organic Search,0,0,0,5.0,674,2.50,Email Opened,India,...,1,0,0,Organic Search,India,Select,Email Opened,Select,Email Opened,Ringing
2,Landing Page Submission,Direct Traffic,0,0,1,2.0,1532,2.00,Email Opened,India,...,0,0,0,Direct Traffic,India,Business Administration,Email Opened,Select,Email Opened,Will revert after reading the email
3,Landing Page Submission,Direct Traffic,0,0,0,1.0,305,1.00,Unreachable,India,...,0,0,0,Direct Traffic,India,Media and Advertising,Unreachable,Word Of Mouth,Modified,Ringing
4,Landing Page Submission,Google,0,0,1,2.0,1428,1.00,Converted to Lead,India,...,0,0,0,Google,India,Select,Converted to Lead,Other,Modified,Will revert after reading the email
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,0,1,8.0,1845,2.67,Email Marked Spam,Saudi Arabia,...,0,0,0,Direct Traffic,Saudi Arabia,IT Projects Management,Email Marked Spam,Select,Email Marked Spam,Will revert after reading the email
9236,Landing Page Submission,Direct Traffic,0,0,0,2.0,238,2.00,SMS Sent,India,...,0,0,0,Direct Traffic,India,Media and Advertising,SMS Sent,Select,SMS Sent,wrong number given
9237,Landing Page Submission,Direct Traffic,1,0,0,2.0,199,2.00,SMS Sent,India,...,0,0,0,Direct Traffic,India,Business Administration,SMS Sent,Select,SMS Sent,invalid number
9238,Landing Page Submission,Google,0,0,1,3.0,499,3.00,SMS Sent,India,...,0,0,0,Google,India,Human Resource Management,SMS Sent,Online Search,SMS Sent,No Comments
9239,Landing Page Submission,Direct Traffic,0,0,1,6.0,1279,3.00,SMS Sent,Bangladesh,...,0,0,0,Direct Traffic,Bangladesh,Supply Chain Management,SMS Sent,Select,Modified,Will revert after reading the email

In [55]:
df4 =df3.drop((df3.select_dtypes(include='object')),axis=1)

In [56]:
df4

,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Search,Newspaper Article,X Education Forums,Newspaper,...,Lead Profile_Other Leads,Lead Profile_Potential Lead,Lead Profile_Select,Lead Profile_Student of SomeSchool,City_Other Cities,City_Other Cities of Maharashtra,City_Other Metro Cities,City_Select,City_Thane & Outskirts,City_Tier II Cities
0,0,0,0,0.0,0,0.00,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1,0,0,0,5.0,674,2.50,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,2.0,1532,2.00,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,1.0,305,1.00,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,1,2.0,1428,1.00,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,1,0,1,8.0,1845,2.67,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9236,0,0,0,2.0,238,2.00,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9237,1,0,0,2.0,199,2.00,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9238,0,0,1,3.0,499,3.00,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
9239,0,0,1,6.0,1279,3.00,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0

In [57]:
X = df4.drop("Converted",axis = 1)
y  = df4[["Converted"]]

In [58]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
scaler = MinMaxScaler()

In [60]:
X = scaler.fit_transform(X)

In [61]:
X

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01992032, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00796813, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.00796813, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01195219, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02390438, ..., 0.        , 0.        ,
        0.        ]])

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
from sklearn.neighbors import KNeighborsClassifier

In [73]:
knn = KNeighborsClassifier()

In [74]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [75]:
y_pred = knn.predict(X_test)

In [76]:
from sklearn.metrics import classification_report

In [77]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1125
           1       0.82      0.73      0.77       690

    accuracy                           0.84      1815
   macro avg       0.83      0.82      0.82      1815
weighted avg       0.83      0.84      0.83      1815

In [78]:
# Ideal Value of K can be determined by Hyperparameter tuning
# GridSearchCV to find optimal min_samples_leaf
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

# parameters 
grid_params = { 'n_neighbors' : [5,7,9,11,13,15],
               'weights' : ['uniform','distance'],
               'metric' : ['minkowski','euclidean','manhattan']}

In [79]:
gs = GridSearchCV(KNeighborsClassifier(), grid_params, verbose = 1, cv=3, n_jobs = -1)

In [80]:

g_res = gs.fit(X_train, y_train)

Fitting 3 folds for each of 36 candidates, totalling 108 fits

In [81]:
# find the best score
g_res.best_score_

0.835789383177485

In [82]:
# use the best hyperparameters
knn = KNeighborsClassifier(n_neighbors = 5, weights = 'uniform',algorithm = 'brute',metric = 'minkowski')
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='brute')

In [83]:
# get a prediction
y_hat = knn.predict(X_train) # training accuracy
y_knn = knn.predict(X_test)  # testing accuracy

In [84]:
from sklearn.metrics import accuracy_score

In [85]:
print('Training set accuracy: ', accuracy_score(y_train, y_hat))
print('Test set accuracy: ',accuracy_score(y_test, y_knn))

Training set accuracy:  0.8746383799421408
Test set accuracy:  0.8358126721763085

RFE Implementation :-

In [91]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import RFE

In [92]:
dt = DecisionTreeClassifier()

In [93]:
df.fit(X_train,y_train)

AttributeError: 'DataFrame' object has no attribute 'fit'